dz4 main page
js-tasks-ru/htmlcss-20240913_dimka1985 pull request #5
Opened 2024-09-22 11:11 UTC by dimarybakov

Домашнее задание по верстке базовой layout страницы

2024-09-22 11:14 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-22 12:06 UTC, GSemikozov requested changes

2024-09-22 12:06 UTC, GSemikozov commented on components/footer/footer.css
> +  padding: 72px 400px 136px;
если добавили контейнер, то здесь уже паддинги по краям не нужны)

2024-09-22 12:06 UTC, GSemikozov commented on components/header/header.css
> +  font-family: 'Inter', serif;
а выше без кавычек; желательно придерживаться одного стиля

2024-09-22 12:06 UTC, GSemikozov commented on index.html
> +      <div class="header">
header

2024-09-22 12:06 UTC, GSemikozov commented on index.html
> +      <div class="main"></div>
main

2024-09-22 12:06 UTC, GSemikozov commented on index.html
> +      <div class="footer">
footer

2024-09-22 17:07 UTC, dimarybakov commented on components/footer/footer.css
> +  padding: 72px 400px 136px;
А как тогда ограничить ширину параграфа в соответствии с макетом?

2024-09-22 17:17 UTC, dimarybakov commented on index.html
> +      <div class="header">
Ой, забыл про семантику. Везде исправлю!

2024-09-22 17:20 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-24 03:43 UTC, GSemikozov commented on components/footer/footer.css
> +  padding: 72px 400px 136px;
ширина в макете - 640, можно так: `max-width: 640px; margin: 0 auto`

2024-09-24 03:44 UTC, GSemikozov requested changes

2024-09-24 03:44 UTC, GSemikozov commented on components/header/header.css
> +  font-family: Inter, serif;
лишнее

2024-09-26 05:50 UTC, dimarybakov commented on components/header/header.css
> +  font-family: Inter, serif;
Понял, почему не нужно - убрал!

2024-09-26 05:50 UTC, dimarybakov commented on components/footer/footer.css
> +  padding: 72px 400px 136px;
Поправил

2024-09-26 16:42 UTC, GSemikozov approved these changes

2024-09-26 16:42 UTC, merged