dz5 buttons
js-tasks-ru/htmlcss-20240913_dimka1985 pull request #6
Opened 2024-09-23 17:12 UTC by dimarybakov

Buttons

2024-09-23 17:12 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-24 03:47 UTC, GSemikozov requested changes

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
ни в коей случае :) наоборот, именно файлы стилей компонентов подключаем в main

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons, .buttons-disabled {
вспомогательная обертка? такие штуки - не часть блока, их не нужно здесь описывать) если нужны такие классы чисто для задачи - можно в отдельном файле стилей

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 190px;
ширину не ограничиваем

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border-radius: 10px;
8

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 190px;
а вот чего не хватает  паддингов

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
лишнее (на кнопке он и так pointer)

2024-09-24 03:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: 1px solid #212429;
можно менять просто border-color

2024-09-26 05:49 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-26 06:08 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-26 06:12 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
Поправил

2024-09-26 06:12 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +.buttons, .buttons-disabled {
Да, это просто для задачи - убрал!

2024-09-26 06:13 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +  width: 190px;
Тогда и высоту, наверное, не нужно ограничивать?
Добавил paddings  сверху и снизу

2024-09-26 06:13 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +  border-radius: 10px;
Поправил

2024-09-26 06:13 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
У меня без pointer не работает!)

2024-09-26 06:14 UTC, dimarybakov commented on 03-lection1/01-button/button.css
> +  border: 1px solid #212429;
Да, дублируется - поправил!

2024-09-26 16:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 190px;
а вот высоту как раз лучше ограничить - нам не нужно чтобы кнопка вырастала в высоту если текст переносится)

2024-09-26 16:43 UTC, GSemikozov requested changes

2024-09-26 16:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 60px;
при таких паддингах высота кнопки точно будет 48? советую все-таки вернуть высоту

2024-09-26 17:16 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-26 19:19 UTC, GSemikozov approved these changes

2024-09-26 19:19 UTC, merged